version: '3.7'

services:  
  server:
    image: gcc:latest
    volumes:
      - .:/tmp/network-programming
    working_dir: /tmp/network-programming
    container_name: server
    ports:
      - 64550:64550
    entrypoint: [ "./execute.sh" ]