version: '3.9'

services:  
  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/tmp/network-programming
    working_dir: /tmp/network-programming
    container_name: server
    ports:
      - 64550:64550
    stop_grace_period: 0s
    entrypoint: [ "./execute.sh" ]
    environment:
      WAIT_HOSTS: redis:6379, postgres:5432
      WAIT_LOGGER_LEVEL: info
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 64549:8080
  redis:
    image: bitnami/redis:latest
    container_name: redis
    environment:
      ALLOW_EMPTY_PASSWORD: yes
      REDIS_PASSWORD: password
    volumes:
      - ./redis:/bitnami/redis/data
  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - 64548:8001
    environment:
      REDISINSIGHT_PASSWORD: password
    volumes:
      - ./redisinsight:/db